services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    build: ./backend
    image: backend
    restart: always
    env_file:
      - .env
    ports:
      - '${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}'
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: frontend
    restart: always
    env_file:
      - .env
    ports:
      - '${FRONTEND_PORT}:80'
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge