services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  backend:
    build: ./backend
    image: backend
    restart: always
    env_file:
      - .env.docker
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge